# Flutter build
name: $(Date:yyyyMMdd)$(Rev:r)
variables:
  - group: 'MyAppSecrets'
  - name : 'projectDirectory'
    value: ''
trigger:
- none
pr:
- none
jobs:
  - job: BuildAndroid
    displayName: ANDROID
    pool:
      vmImage: 'macOS-latest'
    steps:
    - script: dart lib/test.dart