# Flutter build
name: $(Date:yyyyMMdd)$(Rev:r)
variables:
  - group: 'MyAppSecrets'
  - name : 'projectDirectory'
    value: ''
trigger:
  - none
jobs:
  - job: BuildAndroid
    displayName: ANDROID
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        inputs:
          channel: 'stable'
          version: 'latest'

      - task: FlutterBuild@0
        inputs:
          target: apk
          projectDirectory: $(projectDirectory)

      - script: chmod a+x pipelines/scripts.sh
      - script: pipelines/scripts.sh start_android_emulator
        displayName: 'Start android emulator'
      - task: FlutterCommand@0
        displayName: 'Run tests'
        inputs:
          arguments: 'drive --target=test_driver/app.dart'
      - script: pipelines/scripts.sh generate_test_report
        displayName: 'Generate report'

      - publish: $(System.DefaultWorkingDirectory)/test_driver/reports
        displayName: 'Saving reports'
        artifact: reports_android