# Flutter build
name: $(Date:yyyyMMdd)$(Rev:r)
variables:
  - group: 'MyAppSecrets'
  - name : 'projectDirectory'
    value: ''
trigger:
  - none
jobs:
  - job: BuildAndroid
    displayName: ANDROID
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: FlutterInstall@0
        inputs:
          channel: 'stable'
          version: 'latest'
      - task: FlutterBuild@0
        inputs:
          target: apk
          projectDirectory: $(projectDirectory)
      - script: chmod a+x pipelines/scripts.sh
      - script: pipelines/scripts.sh start_android_emulator
        displayName: 'Start android emulator'
      - script: pipelines/scripts.sh flutter_widget_test
          displayName: 'Run Widget test'
      - script: pipelines/scripts.sh flutter_integration_test
        displayName: 'Run Integration test'
      - script: pipelines/scripts.sh generate_test_report
        displayName: 'Generate report'
      - publish: $(System.DefaultWorkingDirectory)/test_driver/reports
        displayName: 'Saving reports'
        artifact: reports_android

  - job: BuildIOS
    displayName: IOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: InstallAppleCertificate@2
        displayName: Install Apple distribution certificate
        inputs:
          certSecureFile: 'my_cert.p12'
          certPwd: '$(iosP12password)'
          keychain: 'temp'
      - task: InstallAppleProvisioningProfile@1
        displayName: Install ad-hoc distribution profile
        inputs:
          provisioningProfileLocation: 'secureFiles'
          provProfileSecureFile: 'BlueSky_InHouse_Certificate.mobileprovision'
      # - task: DownloadSecureFile@1
      #   displayName: Get GoogleService-Info.plist
      #   name: googleServicesInfoPlist
      #   inputs:
      #     secureFile: 'GoogleService-Info.plist'
      # - pwsh: Move-Item $(googleServicesInfoPlist.secureFilePath) ios/Runner/ -Force
      #   displayName: Override GoogleService-Info.plist
      - task: FlutterInstall@0
        displayName: Install Flutter
        inputs:
          channel: 'stable'
          version: 'latest'
      - task: FlutterBuild@0
        displayName: Build app
        inputs:
          target: 'ios'
          projectDirectory: '.'
          buildName: '$(Build.BuildNumber)'
          iosCodesign: false
      - script: chmod a+x pipelines/scripts.sh
      - script: pipelines/scripts.sh start_iOS_simulator 'iPhone 8'
        displayName: 'Start iOS simulator'
      - script: pipelines/scripts.sh flutter_widget_test
          displayName: 'Run Widget test'
      - script: pipelines/scripts.sh flutter_integration_test
        displayName: 'Run Integration test'
      - script: pipelines/scripts.sh generate_test_report
        displayName: 'Generate report'
      - publish: $(System.DefaultWorkingDirectory)/test_driver/reports
        displayName: 'Saving reports'
        artifact: reports_ios
